
## debug/testing/unicodeの3パターン
IF(CMAKE_CONFIGURATION_TYPES)
	set(CMAKE_CONFIGURATION_TYPES Debug RelWithDebInfo Release)
	set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES}" CACHE STRING
	"Reset the configurations to mint style"
	FORCE)

ENDIF()

# Debug
SET(CMAKE_DEBUG_POSTFIX D)

# Testing
SET_PROPERTY(DIRECTORY PROPERTY
    COMPILE_DEFINITIONS_RELWIDHDEBINFO
        NDEBUG
)
SET(CMAKE_RELWITHDEBINFO_POSTFIX T)

# Release
SET_PROPERTY(DIRECTORY PROPERTY
    COMPILE_DEFINITIONS_RELEASE
        LUI_RELEASE
        NDEBUG
)


## 一時ファイル出力先
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY bin CACHE PATH "Output Directory")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY lib CACHE PATH "Output Directory")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY lib CACHE PATH "Output Directory")

## インストール先の初期指定
SET(CMAKE_INSTALL_PREFIX "${CMAKE_HOME_DIRECTORY}/.." CACHE PATH "Install Directory")
