## 環境に応じた定義を定める

## Windows(32bit/64bit)環境
IF(WIN32)
  ADD_DEFINITIONS(-DLUI_USE_WIN32)

  IF(MSVC)
    # 文字コードをunicodeにする
    ADD_DEFINITIONS(-DUNICODE -D_UNICODE)

    # 32bit Windows XP用のコンパイルを指定する
    ADD_DEFINITIONS(-D_WIN32_WINNT=0x0501)
    
    # 余計な警告を抑制する
    ADD_DEFINITIONS(
      -D_CRT_SECURE_NO_WARNINGS
    )
    
    # マルチコアによるコンパイルを有効にする
    ADD_DEFINITIONS(/MP)
    
    # Optimization flags.
    SET(CMAKE_C_FLAGS_RELEASE   "${CMAKE_C_FLAGS_RELEASE} /GL")
    SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /GL")
    SET(CMAKE_EXE_LINKER_FLAGS_RELEASE    "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /LTCG")
    SET(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LTCG")
    SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS_RELEASE} /LTCG")
    
    IF( CMAKE_CL_64 )
      # ローカルLIBの配置
      SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH}
        "$ENV{LIB}/x64"
        "$ENV{LIB}/x64/${MSVC_VERSION}"
      )
    ELSE()
      SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH}
        "$ENV{LIB}/x86"
        "$ENV{LIB}/x86/${MSVC_VERSION}"
      )
      # SSEを有効にする
      ADD_DEFINITIONS(/arch:SSE2)
    ENDIF()
  ENDIF()

ENDIF()

## CYGWIN
IF(CYGWIN)
  ADD_DEFINITIONS(-DLUI_USE_CYGWIN)
  ADD_DEFINITIONS(-D_WIN32_WINNT=0x0501)
  ADD_DEFINITIONS(-D__USE_W32_SOCKETS)
ENDIF()

## UNIX
IF(UNIX)
  ADD_DEFINITIONS(-DLUI_USE_UNIX)
  ADD_DEFINITIONS("-x c++")
ENDIF()

