# mint normal installer

MACRO(LOCAL_INSTALL TARGET_NAME)
	INSTALL(TARGETS ${TARGET_NAME}
		RUNTIME DESTINATION bin
		LIBRARY DESTINATION lib
		ARCHIVE DESTINATION lib
	)
	
	IF(MSVC)
		FOREACH( BCONFIG
			DEBUG
			RELWITHDEBINFO
		)
			GET_TARGET_PROPERTY(OUT_PATH ${TARGET_NAME} LOCATION_${BCONFIG})
			IF( ${OUT_PATH} MATCHES "${CMAKE_STATIC_LIBRARY_SUFFIX}$" )
				STRING(REGEX REPLACE "\\.([a-zA-Z0-9_]+)$" ".pdb" OUT_PATH ${OUT_PATH})
				INSTALL( FILES
					${OUT_PATH}
					DESTINATION lib
					CONFIGURATIONS ${BCONFIG}
				)
			ENDIF()
		ENDFOREACH()
	ENDIF()

ENDMACRO()
