OPTION(LUI_USE_STLPORT "Use STLport." OFF)

IF(CMAKE_CONFIGURATION_TYPES)
	IF( LUI_USE_STLPORT )
		SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_STLP_DEBUG=1")
	ENDIF()
	IF( NOT LUI_BUILD_STATIC_LIBS )
		ADD_DEFINITIONS(-D_STLP_USE_DYNMIC_LIB=1)
	ENDIF()
ENDIF()

